require 'zeus/rails'
require 'guard/titan'

group :zeus do
  guard :titan, root: __FILE__, on_run_all: :recent, exclude_from_all: %w(ob mail) do
    watch /^(.t\/(.*))$/  # run whenever .t/* is touched
    watch(%r|^test/(.*)_test\.rb|)
  end
end
